import './globals.css'
import {  Poppins } from 'next/font/google'

const popins = Poppins({ subsets: ['latin'], weight: ['500', '600'] });

export const metadata = {
  title: 'Shortly',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={popins.className}>{children}</body>
    </html>
  )
}
